version: '2'

services:
    api:
        build: ./api
        volumes:
            - ./api:/api
        ports:
            - 4000:4000
    web:
        build: ./web
        volumes:
            - ./web:/web
        ports:
            - 5000:5000